/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VRFCoordinatorV2_5Mock } from "./VRFCoordinatorV2_5Mock";
export * as factories from "./factories";
export { VRFCoordinatorV2_5Mock__factory } from "./factories/VRFCoordinatorV2_5Mock__factory";
